package in.BidPilots.entity;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.extern.slf4j.Slf4j;

import java.nio.charset.StandardCharsets;
import java.time.LocalDateTime;

@Slf4j
@Entity
@Table(name = "bid_details")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@JsonIgnoreProperties({ "hibernateLazyInitializer", "handler" })
public class BidDetails {

    /**
     * Maximum bytes for MySQL TEXT column is 65,535 bytes.
     * With UTF-8 encoding, each character can take 1-4 bytes.
     * Using 16,000 characters as safe limit (64KB max).
     */
    public static final int MAX_ITEM_CATEGORY_LENGTH = 16000;

    /**
     * Maximum bytes for MySQL TEXT column.
     */
    public static final int MAX_TEXT_COLUMN_BYTES = 65535;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "bid_id", nullable = false, unique = true)
    @JsonIgnoreProperties({ "hibernateLazyInitializer", "handler" })
    private Bid bid;

    @Column(name = "extraction_status")
    private String extractionStatus = "PENDING"; // PENDING, PROCESSING, COMPLETED, FAILED

    @Column(name = "pre_bid_date_time")
    private LocalDateTime preBidDateTime;

    /**
     * Full raw text extracted from the bid PDF document.
     *
     * Stored as MySQL LONGTEXT (up to ~4 GB) so even very large GeM PDFs
     * with hundreds of BOQ line items are stored without truncation.
     *
     * Set to NULL when the bid is finalized to reclaim DB space —
     * see BidAutoCloseService.finalizeOldBidsNow().
     */
    @Column(name = "pdf_content", columnDefinition = "LONGTEXT")
    private String pdfContent;

    /**
     * Item category extracted from the PDF "Item Category" row.
     * Examples:
     *   "Supply of Crane for 40m MLC 60 Bridge"
     *   "Off - Grid Solar Photovoltaic (PV) Power Plant (V2) (Q3)"
     *   "Goods Transport Service - Per KM Based Service -, Household/Office; ..."
     *
     * For BOQ bids with many line items the value is a comma-separated list
     * of all item category names found in the PDF header.
     *
     * Stored as MySQL LONGTEXT to handle large multi-item BOQ bids without
     * "Data too long for column" errors.
     *
     * NULL if the PDF contained no recognisable "Item Category" line.
     */
    @Column(name = "item_category", columnDefinition = "LONGTEXT")
    private String itemCategory;

    /**
     * Safe setter - handles UTF-8 encoding size limits for TEXT column
     * and gracefully truncates oversized values.
     * 
     * This overrides the Lombok-generated setter for this field only.
     * All other setters are still generated by @Setter.
     */
    public void setItemCategory(String value) {
        if (value == null) {
            this.itemCategory = null;
            return;
        }

        // First check by character length (quick check)
        if (value.length() <= MAX_ITEM_CATEGORY_LENGTH) {
            // Verify actual byte size doesn't exceed TEXT limit
            byte[] utf8Bytes = value.getBytes(StandardCharsets.UTF_8);
            if (utf8Bytes.length <= MAX_TEXT_COLUMN_BYTES) {
                this.itemCategory = value;
                return;
            }
            
            // If byte size exceeds, truncate safely
            log.warn("Item category byte size ({}) exceeds TEXT limit ({}), truncating", 
                     utf8Bytes.length, MAX_TEXT_COLUMN_BYTES);
            this.itemCategory = truncateToByteLimit(value, MAX_TEXT_COLUMN_BYTES);
            return;
        }

        // Character length exceeds limit, truncate
        log.warn("Item category length ({}) exceeds max allowed ({}), truncating", 
                 value.length(), MAX_ITEM_CATEGORY_LENGTH);
        
        // Try truncating by characters first
        String truncated = value.substring(0, MAX_ITEM_CATEGORY_LENGTH);
        
        // Verify byte size after truncation
        byte[] utf8Bytes = truncated.getBytes(StandardCharsets.UTF_8);
        if (utf8Bytes.length <= MAX_TEXT_COLUMN_BYTES) {
            this.itemCategory = truncated;
        } else {
            // Further truncate to fit byte limit
            this.itemCategory = truncateToByteLimit(truncated, MAX_TEXT_COLUMN_BYTES);
        }
    }

    /**
     * Truncates a string to fit within specified byte limit when UTF-8 encoded.
     * Ensures we don't cut in the middle of a multibyte character.
     *
     * @param value The string to truncate
     * @param maxBytes Maximum allowed bytes in UTF-8 encoding
     * @return Truncated string that fits within byte limit
     */
    private String truncateToByteLimit(String value, int maxBytes) {
        if (value == null || value.isEmpty()) {
            return value;
        }

        byte[] utf8Bytes = value.getBytes(StandardCharsets.UTF_8);
        if (utf8Bytes.length <= maxBytes) {
            return value;
        }

        // Binary search for the right truncation point
        int left = 0;
        int right = value.length();
        int bestLength = 0;

        while (left <= right) {
            int mid = left + (right - left) / 2;
            String candidate = value.substring(0, mid);
            byte[] candidateBytes = candidate.getBytes(StandardCharsets.UTF_8);
            
            if (candidateBytes.length <= maxBytes) {
                bestLength = mid;
                left = mid + 1;
            } else {
                right = mid - 1;
            }
        }

        String result = value.substring(0, bestLength);
        
        log.debug("Truncated item category from {} chars ({} bytes) to {} chars ({} bytes)",
                 value.length(), utf8Bytes.length, result.length(), 
                 result.getBytes(StandardCharsets.UTF_8).length);
        
        return result;
    }

    /**
     * Helper method to check if current item category would fit in TEXT column.
     * Useful for debugging and monitoring.
     *
     * @return true if item category fits within MySQL TEXT column limits
     */
    public boolean isItemCategoryWithinLimit() {
        if (this.itemCategory == null) {
            return true;
        }
        byte[] utf8Bytes = this.itemCategory.getBytes(StandardCharsets.UTF_8);
        return utf8Bytes.length <= MAX_TEXT_COLUMN_BYTES;
    }

    /**
     * Helper method to get the byte size of current item category.
     *
     * @return byte size in UTF-8 encoding, or 0 if null
     */
    public int getItemCategoryByteSize() {
        if (this.itemCategory == null) {
            return 0;
        }
        return this.itemCategory.getBytes(StandardCharsets.UTF_8).length;
    }
}